#name: ts - CD
#
#on:
#  push:
#    branches: [ main ]
#
#jobs:
#  publish:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#        with:
#          node-version: '12.x'
#          registry-url: 'https://registry.npmjs.org'
#      - name: Install dependencies
#        run: yarn install
#      - name: Build
#        run: yarn build
#      - uses: JS-DevTools/npm-publish@v1
#        with:
#          token: ${{secrets.NPM_TOKEN}}
